pipeline refactoring

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -103,7 +103,7 @@ Promote LiteLLM Image to Prod:
   tags:
     - new_photon_runners
   rules:
-    - if: '$CI_COMMIT_BRANCH == "release"'
+    - if: '$CI_COMMIT_BRANCH == "master"'
   script:
     - >
       echo "Logging into Vault for dev..."; 
@@ -116,11 +116,11 @@ Promote LiteLLM Image to Prod:
       export GCLOUD_PRD_ACCESS_TOKEN=$(vault read -format=json projects/${BUSINESSLINE}-${APPSTACKCODE}/production/gcp/roleset/automation-rw/token | jq -r '.data.token');
 
     - >
-      # Load the dev version used in the last successful build
-      echo "Loading built version from artifact...";
-      if [ ! -f version.env ]; then echo "ERROR: version.env not found. Did you build this version?"; exit 1; fi;
-      source version.env;
-      echo "Loaded dev build tag: $VERSION";
+      echo "Loading built version from artifact..."; 
+      if [ ! -f version.env ]; then echo "ERROR: version.env not found. Did you build this version?"; exit 1; fi; 
+      source version.env; 
+      SOURCE_TAG=$VERSION; 
+      echo "Loaded dev build tag: $SOURCE_TAG";
 
     - >
       VERSION=$(echo "$CI_COMMIT_MESSAGE" | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' || echo "$CI_COMMIT_SHORT_SHA"); 
