pipeline refactoring

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -36,7 +36,7 @@ Sync Upstream:
     - git fetch upstream
     - git checkout update
     - git merge upstream/main --no-edit || echo "Manual conflict resolution needed"
-    - git push origin update
+    - git push "https://gitlab-ci-token:${GITLAB_API_TOKEN}@gitlab.sre.ops.gcloud.thalescloud.io/ccoe/synapse/litellm.git" update
   only:
     - schedules
 
@@ -71,25 +71,26 @@ Generate Version:
       aud: vault
   script:
     - >
-      vault_role=${BUSINESSLINE}-${APPSTACKCODE}-${environment}-infra
-      echo "Logging into Vault... with role: ${vault_role}"
-      vault login -no-print=true $(vault write -field=token auth/jwt/login role=${vault_role} jwt=${VAULT_ID_TOKEN})
+      vault_role=${BUSINESSLINE}-${APPSTACKCODE}-${environment}-infra;
+      echo "Logging into Vault... with role: ${vault_role}";
+      vault login -no-print=true $(vault write -field=token auth/jwt/login role=${vault_role} jwt=${VAULT_ID_TOKEN});
+      if [ $? -ne 0 ]; then echo "Vault login failed!"; exit 1; fi;
       echo "Vault login successful."
     - >
-      echo "Fetching GCP token from Vault..."
-      GCP_TOKEN_JSON=$(vault read -format=json projects/${BUSINESSLINE}-${APPSTACKCODE}/${environment}/gcp/roleset/automation-rw/token)
-      export CLOUDSDK_AUTH_ACCESS_TOKEN=$(echo $GCP_TOKEN_JSON | jq -r '.data.token')
-      export GOOGLE_OAUTH_ACCESS_TOKEN=$CLOUDSDK_AUTH_ACCESS_TOKEN
-      echo "GCP token obtained."
+      echo "Fetching GCP token from Vault...";
+      GCP_TOKEN_JSON=$(vault read -format=json projects/${BUSINESSLINE}-${APPSTACKCODE}/${environment}/gcp/roleset/automation-rw/token);
+      export CLOUDSDK_AUTH_ACCESS_TOKEN=$(echo $GCP_TOKEN_JSON | jq -r '.data.token');
+      export GOOGLE_OAUTH_ACCESS_TOKEN=$CLOUDSDK_AUTH_ACCESS_TOKEN;
+      echo "GCP token obtained.";
     - >
-      echo "Submitting build to GCP Cloud Build..."
-      echo "Project ID: $GCP_PROJECT_ID"
-      echo "Image Name: $IMAGE_NAME"
-      echo "Dockerfile: $DOCKERFILE_PATH"
-      echo "Image Tag: $VERSION"
+      echo "Submitting build to GCP Cloud Build...";
+      echo "Project ID: $GCP_PROJECT_ID";
+      echo "Image Name: $IMAGE_NAME";
+      echo "Dockerfile: $DOCKERFILE_PATH";
+      echo "Image Tag: $VERSION";
       gcloud builds submit --project=$GCP_PROJECT_ID \
         --config=cloudbuild.yaml \
-        --substitutions=_IMAGE_NAME=${IMAGE_NAME},_DOCKERFILE=${DOCKERFILE_PATH},_IMAGETAG=${VERSION},_REGISTRY=${ARTIFACT_REGISTRY_DEV}
+        --substitutions=_IMAGE_NAME=${IMAGE_NAME},_DOCKERFILE=${DOCKERFILE_PATH},_IMAGETAG=${VERSION},_REGISTRY=${ARTIFACT_REGISTRY_DEV};
   dependencies:
     - Generate Version
   needs:
@@ -147,7 +148,7 @@ Promote LiteLLM Image to Prod:
     - >
       echo "$VERSION" | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+$' &&
       git tag -a "$VERSION" -m "Auto-tag from commit message" &&
-      git push origin "$VERSION"
+      git push "https://gitlab-ci-token:${GITLAB_API_TOKEN}@gitlab.sre.ops.gcloud.thalescloud.io/ccoe/synapse/litellm.git" "$VERSION"
 
     - >
       echo "Promoting LiteLLM image $VERSION from dev to prod..." &&
