ci(config.yml): reorder steps - install deps first

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -8,23 +8,6 @@ jobs:
     steps:
       - checkout
       - run:
-          name: Black Formatting
-          command: |
-            cd litellm
-            python -m pip install black
-            python -m black .
-            cd ..
-      - run:
-          name: Linting Testing
-          command: |
-            cd litellm
-            python -m pip install mypy types-requests types-setuptools types-redis types-PyYAML
-            if ! python -m mypy . --ignore-missing-imports; then
-              echo "mypy detected errors"
-              exit 1
-            fi
-            cd ..
-      - run:
           name: Check if litellm dir was updated or if pyproject.toml was modified
           command: |
             if [ -n "$(git diff --name-only $CIRCLE_SHA1^..$CIRCLE_SHA1 | grep -E 'pyproject\.toml|litellm/')" ]; then
@@ -71,6 +54,23 @@ jobs:
           paths:
             - ./venv
           key: v1-dependencies-{{ checksum ".circleci/requirements.txt" }}
+      - run:
+          name: Black Formatting
+          command: |
+            cd litellm
+            python -m pip install black
+            python -m black .
+            cd ..
+      - run:
+          name: Linting Testing
+          command: |
+            cd litellm
+            python -m pip install mypy types-requests types-setuptools types-redis types-PyYAML
+            if ! python -m mypy . --ignore-missing-imports; then
+              echo "mypy detected errors"
+              exit 1
+            fi
+            cd ..
       - run:
           name: Run prisma ./entrypoint.sh
           command: |
